services:

  backend:
    build: .
    container_name: backend-compose
    ports:
      - "8081:8080"

    depends_on:
      mysql-backend:
        condition: service_healthy

  mysql-backend:
    image: mysql:8.4
    container_name: mysql-compose

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backenddevops

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -proot --protocol=tcp --silent"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

volumes:
  mysql-data:
